## Auto-generated by my nix config
[ -f "${ZDOTDIR}/extra.zshenv" ] && source "${ZDOTDIR}/extra.zshenv"

# If you have host-local configuration, this is where you'd put it
[ -f ~/.zshenv ] && source ~/.zshenv
