# referenced from https://github.com/NobbZ/nixos-config/blob/master/.github/workflows/build.yml
name: "Test"
on:
  pull_request:
  push:
jobs:
  builds:
    name: Build configuration for ${{ matrix.host }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - kuro
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
      - uses: cachix/install-nix-action@v13
        env:
          CACHIX_NAME: nixos-nix-install-tests
        # TODO: https://github.com/NixOS/nix/issues/4423, Use latest build https://github.com/NixOS/nix/actions
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/nklm7ficbmx74b2ll6f045z70b1irj6l/install
          install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: ztlevi
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel -L
      - run: nix flake check
