# referenced from https://github.com/NobbZ/nixos-config/tree/master/.github/workflows
# https://nix.dev/tutorials/nixos/build-and-deploy/continuous-integration-github-actions
name: "Test nixos build"
on:
  pull_request:
  push:
jobs:
  builds:
    name: Build configuration for ${{ matrix.host }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - kuro
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
          submodules: true
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: "ztlevi_cache"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel -L
      # - run: nix flake check
